name: Test
on: [push, pull_request]
jobs:
  todo_linux:
    name: Ubuntu Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features

  todo_windows:
    name: Windows Checks
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features

  todo_macos:
    name: Mac OS Checks
    runs-on: macOS-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features

  todo_web:
    name: Web Checks
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        targets: wasm32-unknown-unknown
    - uses: actions/checkout@master
    - name: Run checks
      run: cargo check --package iced_aw --target wasm32-unknown-unknown
    - name: Check compilation of `web` example
      run: cargo build --package web --target wasm32-unknown-unknown